- hosts: web
  become: yes
  tasks:
    - name: Install Python and pip
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Install Flask with/using pip
      pip:
        name: flask
        executable: pip3
        state: present

    - name: Copy app
      copy:
        src: files/app.py
        dest: /home/ec2-user/app.py

    #- name: Run app
    #  shell: nohup python3 /home/ec2-user/app.py &

    - name: Run Flask app in background with nohup
      shell: |
        export FLASK_APP=app.py
        nohup flask run --host=0.0.0.0 --port=80 > /home/ec2-user/app.log 2>&1 &
      args:
        chdir: /home/ec2-user/
