- hosts: web
  become: yes
  tasks:
    - name: Install Python and Flask
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Copy app
      copy:
        src: files/app.py
        dest: /home/ec2-user/app.py

    - name: Run app
      shell: nohup python3 /home/ec2-user/app.py &
