name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install flask

    - name: Test app
      run: |
        python -m unittest discover tests/

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform init & apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve

    - name: Extract EC2 IP and build Ansible inventory
      run: |
        cd terraform
        INSTANCE_IP=$(terraform output -raw instance_ip)
        echo "[web]" > ../inventory/hosts.ini
        echo "$INSTANCE_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ../inventory/hosts.ini

    - name: Set up SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Run Ansible playbook
      run: |
        ansible-playbook ansible/deploy.yml -i inventory/hosts.ini

