name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install flask

    - name: Test app
      run: |
        python -m unittest discover tests/

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform init & apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
        AWS_REGION: ap-southeast-2     
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve -var="MY_PUBLIC_IP=${{ secrets.MY_PUBLIC_IP }}"

    - name: Set up SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Extract EC2 IP and build Ansible inventory
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
        AWS_REGION: ap-southeast-2        
      run: |
        cd terraform

        echo "Getting Terraform output..."
        terraform output

        echo "Fetching instance_public_ip..."
        INSTANCE_IP=$(terraform output -raw instance_public_ip)

        echo "::notice::INSTANCE_IP=<$INSTANCE_IP>"

        if [ -z "$INSTANCE_IP" ]; then
          echo "❌ Failed to get instance_public_ip"
          exit 1
        fi


        echo "✅ IP address: $INSTANCE_IP"
        
        mkdir -p ../inventory
        
        echo "[web]" > ../inventory/hosts.ini
        echo "$INSTANCE_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ../inventory/hosts.ini


        echo "This below is hosts.ini..."
        cat ../inventory/hosts.ini
        echo "This line is at the end of hosts.ini"

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible       
    
    - name: Run Ansible playbook
      run: |
        ansible-playbook ansible/deploy.yml -i inventory/hosts.ini

